# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "a26c0f30a80547b6dc50f9976dfa0f86e9893d89a536a03b3c812c7fad70448e"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"


  depends_on "rust" => :build

  def install
    cd "crates/clnrm" do
      system "cargo", "install", *std_cargo_args
    end
  end

  def test
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")
  end
end
