# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v0.3.3.tar.gz"
  sha256 "a4efc8505e8792b92a9ae5917db89e1b7e64557660a6d5b2a49135311c46a969"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"


  depends_on "rust" => :build

  def install
    cd "crates/clnrm" do
      system "cargo", "install", *std_cargo_args
    end
  end

  def test
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")
  end
end
