# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "0677ed1c820997188b4012471e2d5ddbcbc9b86c63e752cdda6863b8f6f53a3d"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"


  depends_on "rust" => :build

  def install
    cd "crates/clnrm" do
      system "cargo", "install", *std_cargo_args
    end
  end

  def test
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")
  end
end
